site_name: Pathogen NGS Documents
site_description: '病原微生物高通量测序数据分析'
site_author: 'Mark Renton'
site_url: 'https://indexofire.github.io/pangs'
theme: 'material'
copyright: 'Copyright &copy; 2016 - 2017 HZCDCLab'

extra:
  palette:
    primary: 'light blue'

pages:
  - '1.前言': index.md
  - '7.序列比对':
    - '7.1 mafft使用': 07_msa/mafft.md
  - '8.进化树构建':
    - '8.1 数据为基因组序列': 08_phylogeny/building-tree-from-assembly.md
    - '8.2 数据为NGS测序数据': 08_phylogeny/building-tree-from-raw-reads.md

use_directory_urls: true

extra_javascript:
  #- https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/raphael/2.2.7/raphael.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/js-sequence-diagrams/1.0.6/sequence-diagram-min.js
  - https://cdnjs.cloudflare.com/ajax/libs/flowchart/1.6.5/flowchart.min.js
  - assets/js/umlconvert.js

markdown_extensions:
  - codehilite
  - admonition
  - footnotes
  - meta
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.superfences
